OPENAI key support added in; fixed typo in echo statement

diff --git a/SETUP.bash.in b/SETUP.bash.in
--- a/SETUP.bash.in
+++ b/SETUP.bash.in
@@ -12,6 +12,8 @@ export CESIUM_API_KEY="?????????????????????????????????????????????????????????
 # Sign up to the openweathermap.org/api
 export WEATHER_API_KEY="????????????????????????????????"
 
+export OPENAI_API_KEY=??-????????????????????????????????????????????????
+export OPENAI_ORGANIZATION_ID=org-????????????????????????
 
 export BITW_SERVER_PORT=3001
 export BITW_CLIENT_PORT=3002
@@ -38,7 +40,14 @@ if [ $CESIUM_API_KEY == "???????????????????????????????????????????????????????
 fi
 
 if [ $WEATHER_API_KEY == "????????????????????????????????" ] ; then
-    echo "Error: Please edit WEATHER_API_KEY in SETUP.bash to be a valide key" >&2
+    echo "Error: Please edit WEATHER_API_KEY in SETUP.bash to be a valid key" >&2
+    echo "===="
+    return
+fi
+
+
+if [ $OPENAI_API_KEY == "??-????????????????????????????????????????????????" ] ; then
+    echo "Error: Please edit OPENAI_API_KEY in SETUP.bash to be a valid key" >&2
     echo "===="
     return
 fi
